name: Style tests (flake8)

on:
  push:
    branches:
      - main
  pull_request:
    # Run workflow when PR is changed, or when changed from draft to ready
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - '**'

jobs:

  build-and-test:
    name: Style
    runs-on: ubuntu-latest

    # Skip job if it's a draft PR
    if: github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64

      - name: Install models
        run: |
          python --version
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e ./streamflow/
          python -m pip install -e ./streamflow/[dev]

      - name: Run style tests
        run: |
          python run-tests.py --style
