name: Unit tests (python versions)

on:
  push:
    branches:
      - main
  pull_request:
    # Run workflow when PR is changed, or when changed from draft to ready
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - '**'

jobs:

  build-and-test:
    name: Python unit tests
    runs-on: ubuntu-latest

    # Skip job if it's a draft PR
    if: github.event.pull_request.draft == false

    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies
        run: |
          sudo ./.github/workflows/install_dependencies.sh

      - name: print
        run: |
          export SUNDIALS_INST=/usr/local
          export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
          echo $GITHUB_WORKSPACE
          echo $LD_LIBRARY_PATH
          echo $SUNDIALS_INST

      - name: Install models
        run: |
          python --version
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e ./streamflow/
          python -m pip install -e ./streamflow/[dev,cvode]

      - name: run unit tests
        run: |
          python run-tests.py --unit
